### ISSUE TITLE
Allow catchers to return a value

### ISSUE THREAD

**Issue by KashubaK** [Kashuab/ts-throws#13]
```ts
import { throws } from 'ts-throws';

const doSomething = throws((str: string) => {
  const num = parseInt(str);
  if (isNaN(num)) throw new AhCrap();
  
  return num;
}, { AhCrap });

let number = doSomething.try('asdf')
  .catchAhCrap(err => {
    return 0;
  });
  
console.log(number); // -> 0

number = doSomething.try('12')
  .catchAhCrap(err => {
    return 0;
  });
  
console.log(number); // -> 12
```

**Comment by Kashuab** [comment]
I actually don't think this is viable or even desirable. 

- It's nice to know when a catcher was invoked, currently this is supported by the `T | undefined` return type. If the returned value is `undefined`, you know an error was caught and you can guard against applicable logic.
- Devs may want to return a value in a catcher that's not compatible with the original signature, then you have to deal with unions when in 90% of cases it won't be handled at runtime
- `ts-throws` can't reliably detect if _all catchers_ return a value, and omit `undefined` from the resulting return type.

There are workarounds if this behavior is ideal.
